olcf/olcf-user-docs

contributing/index.rst
Missing command from the instructions on step 4.
=> missing instruction

systems/rhea_user_guide.rst
Rhea compiling section was checked. Fixed links and added internal references to make easier the navigation.
=> Rhea compiling

systems/summit_user_guide.rst
=> Fix whitespace in Summit Documentation Resources

systems/summit_user_guide.rst
lots of whitespace issues; needed a lot of newlines for the listed flags/compilers
partially addresses #13
=> Fix Compiling section

systems/summit_user_guide.rst
=> Fix whitespace in Summit System Overview section

systems/summit_user_guide.rst
Fixes minor issues in the Training System section to make it up to date.
Partially addresses #13
=> Fix traning system section

systems/summit_user_guide.rst
Refactors known issues section to reflect a myriad of updates
partially addresses #13
=> Fix known issues section

systems/summit_user_guide.rst
Adds info on vampir/score-p in order to update to WP
Partially addresses #13
=> Fix optimizing and profiling section

systems/rhea_user_guide.rst
=> Fix rhea shell and programming environment section

systems/summit_user_guide.rst
=> Bumps Summit's OS version to RHEL7.6

systems/summit_user_guide.rst
Fixes whitespace and fixes a dead link
partially addresses #13
=> Fix shell and programming env section

systems/summit_user_guide.rst
=> Fix V100 section whitespace

systems/rhea_user_guide.rst, systems/summit_user_guide.rst
Fix errors about undefined labels.
=> fix typo and undefined reference labels

systems/summit_user_guide.rst
=> Added paragraph on login node cgroup

systems/summit_user_guide.rst
=> Updated wording on login node cgroups

connecting/index.rst, getting_started/frequently_asked_questions.rst, getting_started/getting_started.rst, getting_started/olcf_policy_guide.rst, systems/rhea_user_guide.rst, systems/summit_user_guide.rst
=> Updates notes and warnings to reST format

data/policies.rst
This feature is not yet implemented.
=> Removes bullet point on quota auto-alerts

connecting/index.rst, data/transferring.rst, systems/rhea_user_guide.rst, systems/summit_user_guide.rst
=> fix image scaling

systems/summit_user_guide.rst
=> Updates info on BB NFS cache

connecting/index.rst
=> Adds SummitDev fingerprints.

README.md
_Merge after external routes are in place._
Updates `README.md` for production. 🚀
=> Removes pre-production link note

systems/summitdev_user_guide.rst
minor tweak to SummitDev User Guide batch queue policy
=> Adds max running jobs to SummitDev queue policies

accounts/olcf_policy_guide.rst, systems/summit_user_guide.rst
=> Adding preemptable queue paragraph

data/transferring.rst
Adding data transfer examples with some command line tools
=> Add some examples for scp and rsync

systems/summit_user_guide.rst
=> bumps cgroup limits to 16 HWT / 16GB

connecting/index.rst
=> Adds info on system status and scheduled downtimes

accounts/olcf_policy_guide.rst
=> Fixes title in project-centric storage areas

systems/summit_user_guide.rst
closes #86 
We will need to depend on PR reviews to help remember to update this time whenever this section is modified.
=> add last updated time to Summit Known Issues

systems/rhea_user_guide.rst, systems/summit_user_guide.rst
=> add comments about rhea vis tools to summit guide

accounts/frequently_asked_questions.rst
=> Fix mailing address formats

systems/summitdev_user_guide.rst
=> Adds note that SummitDev has no batch nodes

systems/summit_user_guide.rst
=> added section to SUG to point to previous frontier training materials

systems/summit_user_guide.rst
=> Updates Summit overallocation project run limits

contributing/index.rst
Corrections as pointed out by @tom-papatheodore
=> add clarity about updating with upstream

systems/rhea_user_guide.rst
=> Fix up some Rhea moab->slurm stuff, consistentify user{*} to username

systems/summit_user_guide.rst
=> Removes 'ERF allocates incorrect resources' known issue

connecting/index.rst
=> adds note about ORNL-distributed RSA keys

software/analytics/ibm-wml-ce.rst
Updating the IBM WML CE docs in preparation for 1.6.2 being available on Summit.
fyi @bnemanich
=> ibm-wml-ce: Updates for 1.6.2

software/analytics/ibm-wml-ce.rst, systems/summit_user_guide.rst
Add information about the "revision" number in the name of the conda environment.
@grahamlopez @bnemanich
=> ibm-wml-ce: add info on revision number

training/index.rst, training/olcf_gpu_hackathons.rst
This PR partially addresses #167
=> added OLCF GPU Hackathons page to Training

software/analytics/ibm-wml-ce.rst
=> Adds in-context links to IBM WML User Conference Call

systems/summit_user_guide.rst
=> Adds Job Step Viewer to jsrun docs

systems/summit_user_guide.rst
=> Removes malformed comment 

software/UMS/Flux.rst, software/UMS/index.rst, software/index.rst
Fixes #201.
Adds User-Managed Software (UMS) area. Adds Flux Framework project UMS space.
=> Start documentation space for UMS projects

software/software-news.rst
=> Fix CUDA version

index.rst
Adds note to homepage that UAC is still open for support.
=> UAC is still open for support

training/training_archive.rst
This PR adds 3 new events to the training archive.
=> Bring training archive up-to-date as of 2020-03-20

connecting/index.rst
=> Removes italics on system fingerprints table

contributing/index.rst
=> Removes incorrect GitHub guideline

systems/summit_user_guide.rst
I made some minor changes to the formatting, mostly just to comply with reST. If you find anything that needs updating just LMK or feel free to make addt'l commits here.
=> Adds new known issue for setting TMPDIR on Summit

software/analytics/ibm-wml-ce.rst
This PR adds information on how to resolve a common issue encountered by users using PyTorch.
=> ibn-wml-ce: Document solution for parallel dataloader segfault.

systems/summit_user_guide.rst
=> Adds auto-kill info to Summit login node cgroups details

systems/summit_user_guide.rst
=> Added debug queue to Summit user guide

systems/summit_user_guide.rst
=> Adds info on backgrounding job steps

training/olcf_gpu_hackathons.rst
Updated the GPU hackathons page to show correct dates/text for virtual events.
=> Update gpu hackathons page

accounts/olcf_policy_guide.rst
The number was wrong (2) so just updated it to be vague. This also allows this policy page to apply to the AFW as well.
=> Change wrong number of DTNs to vague number

data/archiving.rst
Updating link for HPSS documentation to point to the HPSS Collaboration website
=> Updating link to HPSS documentation

systems/andes_user_guide.rst
=> Updated transition table

training/training_archive.rst
Added 1 entry - including slides/recording - to the training archive and verified that all links work.
=> added GPU performance analysis training to archive

training/training_archive.rst
Added a single event to the training archive and tested locally.
=> Added September training to archive

connecting/index.rst, systems/index.rst
Removes summitdev from user  documentation.
=> Remove summitdev

systems/summit_user_guide.rst
this should be a simple change.
=> spelling error

services_and_applications/slate/overview.rst
Adding more specific information about each user-facing cluster
=> Updating Slate overview

systems/andes_user_guide.rst
updated transition timeline and wording
=> update transition timeline

systems/andes_user_guide.rst, systems/rhea_user_guide.rst
Added a note to the Rhea guide, and edited the note in the Andes guide a little bit.
=> Adding Rhea deprecation message

systems/summit_user_guide.rst
Addresses need to compile on batch node for ME projects.
=> Moderate Enhance Compiling

services_and_applications/slate/use_cases/helm_example.rst, services_and_applications/slate/use_cases/mongodb_service.rst, services_and_applications/slate/use_cases/nginx_hello_world.rst
@olcf/platform-group , minor changes to some of the slate tutorial use cases from recent review.
=> slate tutorial mods

systems/summit_user_guide.rst
Add commentary on having to get an interactive job / batch node for "module" to work.
=> Add comment on modules on rhel8 vs rhel7 MEH login node

software/index.rst, software/workflows/entk.rst, software/workflows/index.rst
This pull request contributes a "software/workflows" directory with a basic EnTK tutorial.
=> Added EnTK workflows tutorial

accounts/frequently_asked_questions.rst
Previous link led to a "File not Found" page. New link was the best I could turn up with a quick google search.
=> Update RSA disposal info

software/analytics/pbdR.rst
Meant to do this ages ago. Better late than never I suppose 😉
=> add basic R/pbdR docs

systems/spock_quick_start_guide.rst
The spock quick-start needed to be updated after changes to slurm's default for `--thread-per-core`
=> update spock quick start after change to slurm

services_and_applications/slate/networking/port_forwarding.rst, services_and_applications/slate/networking/route.rst, services_and_applications/slate/use_cases/mongodb_service.rst, services_and_applications/slate/use_cases/simple_website.rst, services_and_applications/slate/workloads/pod.rst
@kincl , fix for broken image links and clarifications on port forwarding.
=> slate documentation updates

software/e4s.rst
Added Spock info for gcc/10.2.0
Updated Summit info
=> Added Spock info, updated Summit

software/workflows/index.rst, software/workflows/swift_t.rst
This adds a very simple tutorial to the software/workflows/ section for using [Swift/T](http://swift-lang.org/Swift-T/) on Summit. I am tagging @proutrc as a reviewer because he once told me to do that sort of thing.
=> Added workflow tutorial for Swift/T

software/workflows/entk.rst, software/workflows/index.rst, software/workflows/parsl.rst, software/workflows/swift_t.rst
@proutrc, this adds a very simple tutorial to the software/workflows/ section for using [Parsl](https://parsl-project.org/) on Summit.
=> Added Parsl demo to workflow software section

software/e4s.rst
Updated latest e4s package list on spock
=> Spock e4s update

software/e4s.rst
Update module list for E4S 21.08 release on Summit
=> Update summit e4s 21.08

software/workflows/index.rst
Made a few edits for clarity and crispness.
=> A few updates

software/viz_tools/visit.rst
Added a troubleshooting option for those that may be over quota
=> Added to VisIt troubleshooting

software/analytics/ibm-wml-ce.rst, software/python/index.rst
Removed references and examples of deprecated modules and commands
=> Updated the outdated OpenCE page

quantum/quantum_access.rst
Added new hyperlinks to sections
=> Quantum: Re-worded accounts blurb

software/viz_tools/visit.rst
Added syntax for module usage on Andes
Added troubleshooting for hanging connections
=> VisIt: troubleshoot and module updates

training/olcf_gpu_hackathons.rst
Removed specific dates and instead pointed people to main gpuhackathons.org site.
=> updated gpu hackathons page

training/training_archive.rst
This is an update to the training archive - added coding for GPUs using Fortran
=> updated training archive

systems/crusher_quick_start_guide.rst
This PR addresses the observed differences between current and expected behavior for page migration and first allocation with the various allocators.
=> Replacing expected behavior with current behavior for page migration

software/workflows/entk.rst, software/workflows/fireworks.rst, software/workflows/mlflow.rst
@verolero86 Please merge as soon as possible in preparation for the OLCF Users Group meeting on Wednesday. Thank you!
=> Updated demos for workflow modules

systems/andes_user_guide.rst, systems/summit_user_guide.rst
=> Andes,Summit: Updated viz tools references, label

quantum/quantum_systems/rigetti.rst
Removed old systems, added link to new systems
=> Quantum: Updated Rigetti Guide

systems/frontier_user_guide.rst
Removed the reference to launch nodes. Updated the jsrun reference to srun.
=> Corrected the table of node types in overview section

software/analytics/apache-spark.rst, software/analytics/index.rst
1. Added a document  "software/analytics/apache-spark.rst" to setup a spark cluster and run pyspark job a multi-node spark cluster
2. Updated software/analytics/index.rst file
=> User document for Setting up a multi-node Apache Spark cluster and running pyspark job

software/workflows/index.rst, software/workflows/pmake.rst
This adds a description of the pmake workflow tool.
The current tool listings have been alphabetized.
=> Added pmake description.

systems/crusher_quick_start_guide.rst
=> Crusher Guide: fixed typo warnings

systems/crusher_quick_start_guide.rst
Added:
- TRANS op to FP64_FLOPS calculation
- Usage example of rocprof with >1 MPI ranks
- Calculation of theoretical flops on crusher
- Added note for --timestamp on bug in the rocprof section
=> Added to rocprof roofline profiling section

systems/crusher_quick_start_guide.rst
Added calculation for total flops (not just FP64) and corrected a typo in the Arithmetic Intensity calculation.
=> Nick fix arithmetic intensity typo

software/viz_tools/paraview.rst, software/viz_tools/visit.rst
Cleaned up VisIt host profile section, added tabs
Added DVA series tutorials to VisIt and ParaView guides
=> VizTools: Updated VisIt and ParaView guides

systems/summit_user_guide.rst
I added 2 new Known Issues regarding i) GPU-aware MPI on Summit and ii) HIP + GPU-aware MPI on Summit
=> Added 2 new KIs for Summit

software/UMS/index.rst
Adds UMS012 and UMS015 to project listing, adds more details on usage, updates directories used, highlights directory structure for modulefiles written by projects.
=> Jmfinney ums update

services_and_applications/slate/workloads/deployment.rst
Seems like some more syntax changed in openshift. I've updated that but need someone to check.
=> updates to the Deployment tutorial

index.rst, spi/index.rst
=> Add spi section branch

software/software-news.rst
Add darshan-runtime/3.4.0-lite to software news page
=> Add darshan-runtime/3.4.0-lite

systems/summit_user_guide.rst
Update the Summit SPI section to point to the new SPI page.
=> Update Summit SPI

spi/index.rst
Corrected link spelling spi-data-tranfer -> spi-data-transfer
=> Link spelling correction

systems/citadel_user_guide.rst, systems/index.rst
add Citadel to system user guide list
=> Adding Citadel system

software/software-news.rst
Updating software news based on issue identified.
=> Update news to mention issue found with Darshan

spi/index.rst
Changing resources to workflows to correct sentence.
=> Correct workflow wording

systems/frontier_user_guide.rst
This PR syncs the entirety of the profiling section in Frontier user guide with the Crusher user guide. Crusher's user guide has several enhancements as requested by ECP users for more detail on `rocprof` profiling, as well as new sub-sections for HPCToolKit and CrayPat.
=> Synced Frontier profiling section from Crusher profiling section

accounts/documents_and_forms.rst
This note warns users that email templates supersede the online version.
=> Warning on closeout forms.

software/python/conda_basics.rst, software/python/cupy.rst, software/python/index.rst, software/python/miniconda.rst, software/python/parallel_h5py.rst
Overhauled guides, added sphinx tabs syntax
Added instructions for installing conda on Frontier
=> Python: Updated guides with Frontier syntax

software/python/conda_basics.rst, software/python/cupy.rst, software/python/index.rst, software/python/parallel_h5py.rst
Removed Andes from CuPy list (no longer works)
=> Python: Updated typos and bugs in guides

systems/frontier_user_guide.rst
These are the additions to the Frontier users guide for Orion Lustre
=> Suzanne orion

systems/crusher_quick_start_guide.rst, systems/frontier_user_guide.rst
Added preliminary SBCAST section for Crusher & Frontier, under the section heading "Tips for Launching at Scale". I can think of several other subsections that might be good under this heading, including some environment variables or discussion of directory structure within jobs (ie, don't make all ranks write to the same directory).
=> Added SBCAST section to Crusher & Frontier user guides

systems/crusher_quick_start_guide.rst
Updating the details of compiling OpenMP+HIP codes.
=> HIP+OpenMP interoperability section

systems/frontier_user_guide.rst
Added references and polished srun mentions
=> Frontier: added more hyperlinks to transition message

systems/spock_quick_start_guide.rst
Added this to Spock user guide:
=> added warning to spock doc about decommission

quantum/quantum_software/hybrid_hpc.rst, software/python/index.rst, software/python/parallel_h5py.rst
Added unset flag to go with export none flag
=> Python: Fixed slurm scripts

data/index.rst, systems/frontier_user_guide.rst
I added some warnings about Globus not preserving file permissions.
=> Suzanne globus tip

software/UMS/index.rst
System specific updates including projects available, modulefile directories, project directories
=> updated UMS - per system specifics

contributing/index.rst
Added warning for Python 3.10
added specific versions for dependencies
=> Contributing: updated install instructions

systems/frontier_user_guide.rst
First contribution to OLCF User Docs
=> Reformatting the Slurm introduction on Frontier.

systems/frontier_user_guide.rst
Added a 1 MPI per 1 GPU per all L3 cores example
=> Frontier: added new srun example

data/index.rst
Fixed hyperlink target for data retention
=> Data: fixed data retention bug

systems/frontier_user_guide.rst
This PR updates the GPU mapping section and adds a NIC binding section to the Frontier user guide.
=> Update GPU mapping and add NIC mapping

software/software-news.rst, systems/frontier_user_guide.rst
Fixed bug in software news
Fixed bug in Frontier user guide
=> Fixed docs build errors

quantum/quantum_systems/quantinuum.rst
Adding info regarding Quantinuum's new H2 system & assoc policy changes
=> Updating Quantinuum H2 info

software/UMS/index.rst
Basically copy-pasted from the Frontier entry.
=> Add UMS023 HPCToolkit for Crusher

software/viz_tools/paraview.rst, software/viz_tools/visit.rst
Added Frontier syntax for VisIt
Added new ParaView versions for Summit and Andes
=> Viz tools: updated visit and paraview guides

accounts/accounts_and_projects.rst
Swapped Summit to Frontier stats
=> Accounts: updated guidance on alloc requests

systems/2023_olcf_system_changes.rst, systems/index.rst
Initial 2023 system changes page
=> Add new 2023 changes page

software/python/cupy.rst, software/python/index.rst, software/python/miniconda.rst
Re-added Andes back to CuPy guide
Rearranged conda guide warnings
=> Python: updated CuPy,conda guides

training/olcf_gpu_hackathons.rst
This updates links to the Open Hackathon page as well as details on the GPU hackathon page.
=> Openhackathons

quantum/quantum_access.rst, quantum/quantum_systems/index.rst, quantum/quantum_systems/ionq.rst
Basic IonQ user guide and mention in how-to-access section.
=> Adding IonQ to available quantum systems

contributing/index.rst
Added version required for sphinx panels
=> Updated contributing section

systems/andes_user_guide.rst
Changed table to extend GPU policy for using greater than 2 nodes
=> Andes: changed GPU policy

systems/frontier_user_guide.rst
Adds information about the newly installed PE and ROCm modulefiles.
=> Update Frontier guide with latest software versions

quantum/quantum_systems/ionq.rst
Added additional content to the IonQ user guide in the docs.
=> Upgrading IonQ user guide

conf.py, quantum/quantum_software/hybrid_hpc.rst, services_and_applications/jupyter/overview.rst, software/UMS/index.rst, software/debugging/index.rst, software/profiling/Scorep.rst, software/python/cupy.rst, software/python/index.rst, software/python/parallel_h5py.rst, software/viz_tools/paraview.rst, software/viz_tools/visit.rst
=> Convert pages to use sphinx_design

services_and_applications/slate/getting_started.rst, services_and_applications/slate/image_building.rst, services_and_applications/slate/use_cases/minio.rst, services_and_applications/slate/use_cases/mongodb_service.rst
This updates the oc login commands for specifying the username flag needed for newer clients.
=> update oc login commands for specifying the username flag

software/containers_on_summit.rst
Updated docs for Summit Plus and the new olcf base images.
=> WIP: Updated docs for summit plus containers

software/python/conda_basics.rst, software/python/cupy.rst, software/python/index.rst, software/python/parallel_h5py.rst
also added sphinx design syntax to python guides
=> Python: updating Summit install syntax

systems/frontier_user_guide.rst
Hopefully this can get merged before the OLCF March 2024 GPU hackathon.
=> Frontier: Update HPCToolkit section

services_and_applications/jupyter/overview.rst, software/python/index.rst, software/python/jupyter_envs.rst, software/python/sbcast_conda.rst, systems/frontier_user_guide.rst
Added new jupyter env creation guide
Fixed some typos in the new sbcast section
=> Updated Jupyter and Python sections with new guide

software/python/index.rst, software/python/pytorch.rst, software/python/pytorch_summit.rst
=> Added software page for PyTorch

quantum/quantum_software/hybrid_hpc.rst, software/python/conda_basics.rst, software/python/cupy.rst, software/python/index.rst, software/python/jupyter_envs.rst, software/python/parallel_h5py.rst, software/python/sbcast_conda.rst
Renamed miniforge module
Also added conda init warning
=> Python: updated new module syntax

quantum/quantum_systems/ibm_quantum.rst
Updated documentation to reflect transition from reservations to sessions.
=> Updated IBM policy on reservations and sessions

quantum/hello_qcup.rst, quantum/index.rst, quantum/quantum_access.rst, quantum/quantum_software/hybrid_hpc.rst
Moved example scripts to Hello QCUP
Cleaned up and expanded Hybrid HPC page
=> Quantum: Added Hello QCUP page

spi/index.rst
Chris informed me that the login process for Frontier SPI is different from KDI vs whitelisted SPI.
=> Fixing KDI vs SPI differences

quantum/quantum_systems/ionq.rst
Added instructions to IonQ Allocations & Credit Usage section for users to submit an allocation request.
=> updating IonQ allocation request policy

systems/2024_olcf_system_changes.rst
Update new dates in system change page
=> Update dates in 2024_olcf_system_changes.rst

quantum/quantum_systems/quantinuum.rst
Updating wording to remove mention of max qubit count given QTM's increasing upgrade frequency
=> updating Quantinuum docs

systems/frontier_user_guide.rst
Added new bullet points to highlight changes to PrgEnv-amd and PrgEnv-gnu in CPE/23.12.
=> Added specific information for PrgEnv-amd and PrgEnv-gnu changes

quantum/quantum_software/hybrid_hpc.rst, software/debugging/index.rst, software/python/cupy.rst, software/python/parallel_h5py.rst, software/python/pytorch_frontier.rst, software/python/pytorch_summit.rst, software/python/sbcast_conda.rst
Fixed Python guide syntax
Fixed quantum syntax
Fixed mention in debugging section
=> Cleaning up mentions of amd-mixed and numpy

systems/2024_olcf_system_changes.rst
Adding the hsi_xfer tool and separating HPSS and Summit timelines
=> Adding hsi_xfer

software/viz_tools/paraview.rst
Added ums and cleaned things up into tabs
=> ParaView: Added Frontier UMS

software/containers_on_frontier.rst
This is just a draft. Several of the containers still need to be built (all need to be tested). And I plan to write an example of how to build in the container off-site and then run it on frontier by binding in the libs using lammps.
=> Added initial layout. Next step added lammps workflow example

quantum/quantum_access.rst, quantum/quantum_systems/index.rst, quantum/quantum_systems/iqm.rst
Adding IQM guide to documentation, added IQM to quantum systems index, and added IQM section to quantum access page.
=> Adding IQM guide to docs

quantum/quantum_systems/quantinuum.rst
added nexus references
restructured a bit
=> Quantum: updated quantinuum guide

systems/frontier_user_guide.rst
Added system update section for Jan 14 outage, added CPE 24.11 to docs
=> Added system update section for Jan 14 outage, added CPE 24.11 to docs

software/software-news.rst, systems/frontier_user_guide.rst
Also triggers a re-build of the Known Issues list, which has been updated.
=> Updated to make verbs past-tense for February 18 outage

conf.py, systems/frontier_user_guide.rst
Added a DataTable for users to be able to easily search Frontiers Known Issues
=> Adding Frontier Known Issues Table

software/UMS/index.rst
removed old projects, added new projects
converted to list-table
=> UMS: updated and overhauled table

software/software-news.rst
Added a Software News announcement for the addition of Core/25.03 to Frontier
=> Software News: Core/25.03 Announcement

software/analytics/pytorch_frontier.rst
The pyTorch on Frontier RCCL plugin guide was missing some of the current best recommendations for settings at scale, in particular critical information to avoid `FI_MR_CACHE_MONITOR=memhooks`, some useful libfabric settings, and how to use the `alt_read` protocol.
It would be nice to have these in before the AI hackathon.
I suggest review by @michael-sandoval , since he wrote the original guide. I'll ask a few HPE and AMD folks to look as well and make sure I didn't make any mistakes.
=> [rccl] Update pyTorch guide to include new RCCL flags

systems/frontier_user_guide.rst
Trying to be slightly more verbose/exact and include a clear-cut Recommended User Action section in each post based on feedback from the user survey.
=> Update Frontier Outage notes for May 13 outage

data/index.rst, systems/frontier_user_guide.rst
Added debug and partition info to frontier guide
Added example to purge section
=> Modified Frontier and Purge guides

software/viz_tools/paraview.rst
Updating to add newly installed versions of Paraview
=> updating Andes paraview versions to include 6.0.0
