systems/summit_user_guide.rst

Fixes whitespace issues, a few dead links, and a table format error.
partially addresses #13

Fix running-jobs section

---

systems/summit_user_guide.rst

Fix all of the links on the Summit page to be cross-reference links in order to ensure that, if sections change names, the links will maintain the correct relative location and title
partially addresses #13 
note: the link to #hpss-best-practices was not fixed, as that section does not exist yet/will be moving. (#15)

Add cross ref links to Summit page

---

getting_started/documents_and_forms.rst
getting_started/frequently_asked_questions.rst
getting_started/getting_started.rst
getting_started/index.rst
getting_started/olcf_policy_guide.rst
systems/index.rst
systems/rhea_user_guide.rst
systems/summit_user_guide.rst

Partially addresses #10.
This fixes all of the external links in the "Getting Started" pages, and most of the internal links as well. The only ones I noticed that are not fixed by this PR are those referencing file systems and DTNs, as we do not have the local "Data" pages installed yet.

fix broken wordpress links in getting started

---

systems/summit_user_guide.rst

Changes wording to direct readers to the `bsub` man page for additional info.

Removes broken link to additional bsub info

---

index.rst
training/index.rst

For consistency, all top-level sections should be in the sidebar. Since there is nothing from "training" locally hosted, this just goes to a page with the external links. Other suggestions welcome.
Closes #46

WIP: put training into sidebar

---

systems/summit_user_guide.rst

Adds final section `Preparing for Frontier`, which only existed on WP
Partially addresses #13

Add preparing for frontier section

---

training/index.rst

Resolves #75. There are newer/more relevant tutorials on the OLCF-Tutorials GH org.

Corrects training link to OLCF-Tutorials on GitHub

---

_static/css/theme_overrides.css
_static/width.css
_templates/layout.html
conf.py

This commit replaces hardcoded template styling blocks and stylesheet
references generated by injecting them into the HTML template context
with having all stylesheets applied by the theme engine according to the
[theme documentation for adding custom CSS](https://docs.readthedocs.io/en/latest/guides/adding-custom-css.html)
and the associated [Sphinx custom CSS configuration documentation](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files).
In conjunction with this change, all the custom styles are merged into a
single stylesheet and style blocks have been removed from the page
templates.

Updates CSS theme overrides.

---

systems/index.rst
systems/rhea_user_guide.rst
systems/summit_user_guide.rst
systems/summitdev_user_guide.rst

Adds SummitDev User Guide

---

index.rst

The landing `index.rst` for the User Docs feels a bit empty. Here's a minimalistic first effort... any others have thoughts?

Add body text to landing page

---

systems/summit_user_guide.rst

New `cgroups` policies are difficult to describe. Hopefully this PR clears things up a little bit.

Clarify Summit login node cgroup policy

---

_static/js/custom.js
conf.py

This PR makes it easier for readers to propose improvements or directly contribute documentation corrections via the familiar "Edit on GitHub" button in the upper-right corner of each page.
Clicking this "Edit on GitHub" link will redirect to the current page's `.rst` file in this repository, and if the edit (pencil icon) button is clicked, a fork of the repository will automatically be made to facilitate making a PR.
This PR maintains the existing "OLCF Home Page" navigation button on each page.

Adds `Edit on GitHub` button alongside OLCF home page navigation

---

connecting/index.rst
systems/ascent_user_guide.rst
systems/dtn_user_guide.rst
systems/home_user_guide.rst
systems/hpss_user_guide.rst
systems/index.rst
systems/rhea_user_guide.rst

Collect systems in a single section

---

accounts/frequently_asked_questions.rst
index.rst

closes #70.
One thing: clicking on the "Getting Help" link takes you to the right place, but since it is the last FAQ entry, it isn't at the top of the page (depending on your browser window size), and so it may not be immediately obvious where you have been taken. I couldn't think of a better place to put this short section, but open to suggestions.

add some best practices for submitting tickets

---

systems/rhea_user_guide.rst

Add the flag to declare how to allocate all the memory on Rhea node. Moreover the double dashes "--" where not appeared correct, we need to use \\-\\-. This also closes #113

Rhea memory flag

---

systems/rhea_user_guide.rst

Removed the step showing how to get an interactive job with Torque/Moab and replaced it with the salloc equivalent.

Nicedcv to slurm

---

systems/summit_user_guide.rst

Now that it has been decommissioned, Titan should be discussed in the past tense. 
Fixes #158, among other minor corrections.

Corrects a few references to Titan

---

conf.py

As described in #109, the default Sphinx behavior for naming pages isn't very clean (at least in our existing structure).
This PR uses [html_title](http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_title) to force all page titles to read `<Page Title> - OLCF User Documentation`.
This fixes #109.

Removes extra `documentation` on page titles

---

systems/summit_user_guide.rst

This is a partial review of Summit's Known Issues section.
The main change here is a move of the `FAULT_TOLERANCE` issue to resolved. Previously, setting `FAULT_TOLERANCE=1` in `~/.jsm.conf` would cause job launch to fail. This is reported fixed by IBM, and I have confirmed with a small job that launch works when this is set in the current software stack.

Moves FAULT_TOLERANCE Issue to Resolved

---

systems/summit_user_guide.rst

This PR moves the known issue titled "-g flag causes internal compiler error with XL compiler" into the resolved heading.

known issue that caused XL ICE when using -g flag moved to resolved

---

contributing/index.rst

I am guessing the name of the repo started as olcf-user-documentation and changed to olcf-user-docs at some point. The GitHub auto-redirect for the OLCF master repo is working fine but we should still update the name inside the docs for contributing, since it will be relevant for people who fork the repo.

Update name to olcf-user-docs

---

systems/summit_user_guide.rst

This PR describes the common issue that occurs when a serial application is launched with jsrun and gets a CUDA hook error. This can also happen if you call into CUDA before MPI_Init(). Two workarounds are proposed. Note that while I'm submitting this to Open Issues, this is really a design choice by IBM that has been carefully considered and has reasons for being designed the way it is, so it is not something that they are intending to change in the near future as far as I know.
Closes #78

Add description of CUDA hook issue and workarounds

---

conf.py

On a system I was using where I was using sphinx and sphinx-rtd-theme from Ubuntu rather than from pip, my version of sphinx-build was old enough (1.6.7) that the RTD theme didn't work without specifying `master_doc`. I found the solution on SO:
https://stackoverflow.com/questions/56336234/build-fail-sphinx-error-contents-rst-not-found
which is consistent with the Sphinx documentation:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-master_doc
I tested this on both my older install that required it, and a newer one that didn't, and it works for both cases.

Specify master_doc to avoid issues with older versions

---

training/index.rst
training/training_archive.rst

This PR adds the Training Archive section to the new OLCF docs. It partially addresses #167

added training archive to docs

---

software/analytics/ibm-wml-ce.rst

@grahamlopez 
The Horovod version wasn't updated in the cloning instructions when we changed verisons, and I added some clarification regarding horovod to the cloning instructions. Let me know if you'd like me to make any changes.
@bnemanich @nvcastet

ibm-wml-ce: update horovod install instructions

---

software/index.rst

Removes 'at the OLCF' from Software section title

---

_static/css/theme_overrides.css

Fixes #91.
This change enables horizontal scrolling for tables of class `.wy-table-responsive` when the content would otherwise not be visible (small widths that aren't small _enough_ to toggle mobile media queries).
Note that to pick up this change, for review and in production, one may need to clear their browser's cached styles.

Enable horizontal scrolling for tables at lower widths

---

systems/summit_user_guide.rst

This documents a known incompatibility between the NVIDIA Nsight Compute command-line profiler and Spectrum MPI, and describes how to work around it.

Note Spectrum MPI + Nsight Compute incompatibility

---

data/archiving.rst

Completes `htar` codeblock for member files > 64GB

---

_static/css/theme_overrides.css
_static/js/custom.js
conf.py

Fixes #6 
With some elbow grease, anything is possible...

Adds OLCF logo to user docs

---

training/training_archive.rst

I changed the Training Archive to contain one large table of events - sorted by date - where each entry includes the date, title, speaker, event, slides, and recording.

Changed layout of Training Archive to table entries

---

_static/js/custom.js

Adds external link icons to main nav

---

software/analytics/ibm-wml-ce.rst

- Added the new package versions.
- Removed IBM DDL specific tuning parameters that aren't needed anymore.
- Added explicit information about loading specific module versions.
We should wait for @mpbelhorn to install the module, and I think we may be waiting for an announcement, since this version will be moving from Tensorflow 1 to 2 and may break people's scripts if they're just doing `module load ibm-wml-ce`
@bnemanich @nvcastet

ibm-wml-ce: Changes for 1.7.0

---

software/analytics/ibm-wml-ce.rst

The horovod build instructions are no longer needed, and I updated the version numbers in some of the examples to be more up to date.

ibm-wml-ce: Remove horovod build instructions and update versions.

---

software/index.rst

Resolves #223. Adds external link to software news on olcf main site. 
Will migrate content in a separate issue.

Adds link to Software News

---

software/index.rst
software/software-news.rst

Resolves #225
This commit migrates the Software News section of the OLCF website into this
repository. Migrated content only extends back to March 12, 2019 for currently
deployed systems.
This commit also sets a format for additional entries in the Software News
page. Notably, raw HTML is used to define titles, as to keep them out of the
main navigation and create subsection bloat. It also uses separators
to draw horizontal lines on the page between each announcement. CSV tables
are used for module changes, as they're significantly easier to maintain than
normal-format reST tables.

Migrates Software News section to this repo

---

software/software-news.rst

The second table just shows new versions deployed, not new defaults. This fixes that header.

New versions of SW not Default SW

---

systems/summit_user_guide.rst

This was introduced with SMPI 10.3.1.2 and a bug has been opened with IBM.

Add segfault on login node to known issues

---

data/project_centric.rst
data/user_centric.rst

Fixes #153.
It seems this was dropped in the docs migration to GitHub. I've updated the language, but otherwise a pretty direct carryover.

Adds info about NFS backup snapshots

---

systems/summit_user_guide.rst

Add NVIDIA Nsight Systems and Nsight Compute documentation

---

systems/summit_user_guide.rst

JSV now available on Ascent; removes Summit-only limitation.

Update Job Step Viewer limitations

---

systems/summit_user_guide.rst

This MR closes #73. In the process, it 
* Adds a new section "Allocation-Wide Options" (aka anything controlled by `-alloc_flags`)
* Moves "MPS" into a subsection of it
* Moves "Hardware Threads" into a subsection of it
* Adds a subsection "GPU Compute Modes" (where #73 is met).

Collects alloc_flags values into a single section

---

services_and_applications/slate/access_olcf_resources/index.rst
services_and_applications/slate/access_olcf_resources/job_submit.rst
services_and_applications/slate/access_olcf_resources/mount_fs.rst
services_and_applications/slate/index.rst

Adds documentation about how to access OLCF resources from containers running in Slate

Adding Slate doc on integration with existing OLCF resources

---

training/training_archive.rst

This PR adds 2 training events from June to the training archive. The sphinx build was also complaining about a title overline being too short so I increased its length.

added June events to training archive

---

systems/summit_user_guide.rst

Addresses #297 
Added some clarifying phrases to explain what the btio binary is doing
in the job script examples in the tables, in the NVMe usage section for Summit.
Other minor clarity corrections.

Fixing clarity issues in NVMe usage example in the Summit doc

---

systems/summit_user_guide.rst

This is important to emphasize in our docs because the man pages
for jsrun can list different defaults than what we set on the machines
and so users can get confused. Having a warning here would be useful.

Updated wording about olcf defaults differing from man page values

---

software/analytics/ibm-wml-ce.rst

Deprecates the `ddlrun` tool and documents best practice for using `jsrun`.
Resolves #266
@bnemanich

IBM WML-CE: Deprecate ddlrun.

---

contributing/index.rst

- After step 4, we are already in olcf-user-docs directoy. Thus, 'cd olcf-user-docs' should be ommited in step 5.
- Document root is technically precises, it might be helpful to state '_build'

Be even more precise in steps

---

systems/summit_user_guide.rst

Adding a tutorial github link at top of the Summit doc.
This came after a suggestion from a new user who was overwhelmed from navigating the Summit doc and had found those github tutorials very helpful in providing context and practical examples.

Adding a link to our tutorials and examples page 

---

systems/summit_user_guide.rst

Required on Moderate Enhanced to re-source the environment, similar to interactive use.

Add -l to job script example

---

systems/summit_user_guide.rst

Updating the overall limit of jobs in the batch-hm queue on Summit (was 100, now is 25)

Updating Summit's batch-hm policy

---

data/policies.rst

Added tip about jobs failing due to home directories being over quota; cleaned up definitions under the table to make it a bit easier to read.

Batch job quota issue

---

systems/spock_quick_start_guide.rst

I updated the GPU Mapping section of the Spock user guide to use `--gpus-per-task` for 1-MPI-per-GPU examples and `--ntasks-per-gpu` for multiple-MPI-per-GPU examples. I also added 2-node versions of each example as well.

Updated GPU mapping section of Spock quick-start

---

software/e4s.rst
software/index.rst

Added information for loading the E4S meta module on Summit.
Added E4S page link to Software page.

Add E4S documentation

---

services_and_applications/slate/networking/nodeport.rst

clarify NodePort document by referencing a service created by the services doc

slate:networking::nodeport: clarify NodePort doc

---

systems/spock_quick_start_guide.rst

Changed the single word CUDA to HIP.

fixed typo from CUDA to HIP

---

systems/andes_user_guide.rst
systems/summit_user_guide.rst

Was adding a myOLCF link to the Summit page when I noticed the discussions of job accounting differed slightly between the Summit and Andes guides, and the Andes guide had an old link for myOLCF. Modified to make the two pages consistent, to link to the new myOLCF, and to update references form 'My OLCF' to the newer 'myOLCF' styling.

Summit myolcf update

---

systems/summit_user_guide.rst

I've added a section explaining the use of OMP_NUM_THREADS. I've reworked the docs a little so that the Job Launcher (jsrun) section is broken out into more pieces to give more visibility to the subsections that were usually hidden under Job Launcher (jsrun) and were hard to find.
You will want to pull my branch locally and build it with sphinx to see how it looks on the rendered webpage.

restructuring multithreading information for Summit jobs

---

systems/spock_quick_start_guide.rst

I added PrgEnv-amd instead of "not yet available" and removed GCC from the list of compilers with OpenMP offload support in the Spock docs.

added PrgEnv-amd and removed gcc from omp offload

---

software/software-news.rst

DALI has been added back into OpenCE. Release date is currently set for Dec 29th.

Software news about OpenCE 1.5.0 on Summit

---

systems/crusher_quick_start_guide.rst

The number of MI250X in Crusher was accidentally listed as 1536 (which is the number of GCDs not MI250X). This PR changes that number to be the correct value of 768.
192 compute nodes * (4 MI250X / compute node) = 768 MI250X
192 compute nodes * (4 MI250X / compute node) * (2 GCDs / MI250X) = 1536 GCDs

corrected MI250X count to 768 instead of 1536 (which is GCD count)

---

systems/crusher_quick_start_guide.rst

Update to Crusher Quick Start guide. 
* Adding a section that documents important differences between Summit and Crusher. 
* To be populated with more information in the future.
* Initially documenting differences in denorm, 'flush to zero' behavior on MI250X and V100.

Adding 'Differences between Summit and Crusher' Section

---

systems/summit_user_guide.rst

Consolidated Citadel information to its own section
Removed references to mismatched OS versions on Citadel

Summit Guide: reorganized SPI Citadel mentions

---

systems/crusher_quick_start_guide.rst

Compatibility between cray-mpich and rocm is not guaranteed across multiple versions. This commit adds documentation to help the user determine a compatible pairing of cray-mpich and rocm.

MPICH and ROCm compatibility on Crusher

---

systems/crusher_quick_start_guide.rst

Added `HIP + OpenMP CPU Threading` section following the HIP section to describe process for compiling hybrid CPU threading and HIP codes.

Added HIP + OpenMP Host Threading section

---

software/software-news.rst

Announcement for the 1.5.2 release of open-ce. 1.5.3 is also out, but only includes updates for power10. The date is marked as today, but can be changed to whatever seems appropriate.

open-ce 1.5.2 release

---

systems/crusher_quick_start_guide.rst

The --gpus-per-task option is currently difficult to use due to how Slurm works on Crusher's compute nodes. This commit reworks the current examples to use either --gpus or --gpus-per-node to get the desired binding. An example of how to run the test case of a single task with a single GPU is also included.

rework gpu binding examples on crusher

---

systems/crusher_quick_start_guide.rst

This adds a table for users to track the compatibility of rocm and cray-mpich modules on crusher. This makes the above text on determining compatibility more concrete.

Add compatibility table for rocm and cray mpich

---

systems/summit_user_guide.rst

The name and behavior of the HIP module on Summit has changed.
There is probably more that can be said about what this release offers, specifically in regards to the new HIP marshalling libraries used for the cuda math libraries. That might be a larger documentation effort though, and I'm not sure it should delay correcting this piece now.

Update HIP module info on Summit

---

software/containers_on_summit.rst
systems/summit_user_guide.rst

Added two sections in Containers on Summit talking about single node
GPU program and a GPU aware MPI program. Both work on Summit if the steps are
followed.
Also added info about the seg fault you'll see if you don't use the right
flag for GPU aware MPI, and corrected some inconsisten capitalization in the
Summit guide.

Adding sections for GPU containers

---

systems/crusher_quick_start_guide.rst

Added a section to detail some very basic rocprof usage - 'rocprof --stats'. Also added a section about how to generate a simple operational roofline model using rocprof metrics. Fairly limited example (ignores matrix instructions), but it should be able to generate correct rooflines. Rocprof's timestamps aren't fully accurate at this moment (BeginNs is not appearing to be correct), so maybe adding a warning to the doc is needed as well.

Added section for profiling and roofline profiling

---

systems/crusher_quick_start_guide.rst

Fixed a typo in the body of paragraphs that referred to L2 write/read request as WREQ and RREQ, instead of their correct naming - WRREQ, RDREQ.

Fixed typo in RDREQ and WRREQ metrics of rocprof section

---

systems/frontier_user_guide.rst

Feel free to reject, but I'd like to propose adding \text to make equations in roofline profiling section more clear. This also makes the subscripts render correctly.

Update Roofline Profiling Equations in frontier_user_guide.rst

---

systems/frontier_user_guide.rst

Replacing "Summit" (OLCF-4) with "Frontier" (OLCF-5). Two instances were found and changed.

Replace "Summit" with "Frontier" in text

---

systems/frontier_user_guide.rst

Clarify bi-directional bandwidth phrasing
Priority had a typo (missing y)

Minor Edits to User Guide Language

---

systems/crusher_quick_start_guide.rst

New in this PR:
- Added MFMA matrix instructions to the calculation of total performed FLOPS for rocprof. This is consistent with information provided from AMD. Matrix FMA instructions should be multiplied by 512 to calculate the total FLOPS from that operation.

Added MFMA_MOPS instruction to FP64 calculation of rocprof roofline

---

systems/crusher_quick_start_guide.rst

Guidance on potential low performance of HW LDS FP32 atomicAdd() on MI200.

HW LDS FP32 atomicAdd guidance for Crusher

---

systems/summit_user_guide.rst

The added section points to the modulefile for the newest HPCToolkit release version 2022.10.01.
Tested locally on my laptop.

Add HPCToolkit section on Summit user guide

---

systems/crusher_quick_start_guide.rst

This PR simply points to the updated Frontier node diagram that includes the 4 IF links between the GCDs on a common MI250X instead of a single darker red line. Until this PR is merged, you can see the difference between the Crusher and Frontier node diagrams in their user guides. 
The `diff` is literally:
```
-.. image:: /images/Crusher_Node_Diagram.jpg
+.. image:: /images/Frontier_Node_Diagram.jpg
```

pointed Crusher quick-start to correct node diagram

---

systems/crusher_quick_start_guide.rst

This PR updates the Crusher Quick-Start examples with correct mappings that will be in effect after the outage on 12/29.

Update examples due to config changes on 12/29

---

systems/crusher_quick_start_guide.rst
systems/frontier_user_guide.rst

Based on information from https://gpuopen.com/learn/amd-lab-notes/amd-lab-notes-matrix-cores-README/
Namely, the number of Flops/Clock/CU is DIFFERENT for different precisions. FP32 & 64 have 256, while INT8, FP16, and BF16 have 1024 (4x!). This link is a blog written by AMD, and I have cross-referenced these numbers to the GFX90A/MI250X whitepaper.
I could use a set of eyes on how this is formatted, in addition to whether the information is correct. I want to make sure this makes sense to folks who have less experience with roofline modeling or hardware counters.

Update flop counter for precisions in roofline model

---

systems/crusher_quick_start_guide.rst
systems/frontier_user_guide.rst

Compresses the metrics in the input.txt for roofline so that the application is re-run only twice (compared to 5x, previous).

Compress metrics to reduce  reruns in rocprof input file

---

systems/summit_user_guide.rst

HIP code on Summit cannot be compiled when relying on HIP language support or hip::device and hip::host keywords. For HIP language support, CMake relies on using `hipconfig --rocm-path`, which on Summit, evaluates to `/opt/rocm`, which doesn't exist. `hip::device` and `hip::host` are defined in a CMake file in `lib/hip/cmake` that is not present in the `hip-cuda` installation, but is present in ordinary ROCm installations. So these keywords have no meaning on Summit, leading to compile failures.

Added KI for CMake on Summit for HIP

---

systems/frontier_user_guide.rst

Added information regarding core specialization & low-noise mode to Frontier user guide. I built locally, and the changes rendered as expected.

Add corespec & Low-noise mode note to frontier

---

systems/crusher_quick_start_guide.rst

sleep is currently required between job steps launched in the background. Without it, users will encounter MPICH ERROR. Other workarounds are described in a Crusher known issue.

Added sleep to the simultaneous job example. Not needed for Frontier

---

systems/crusher_quick_start_guide.rst
systems/frontier_user_guide.rst

The AQL library is needed whenever using `rocprof` or `omniperf`. It is not detected by `ld`, since it is `dlopen`'d.
This library is opened regardless of whether any profiling is done or not, but the program will abort if you try to profile without it.

Added AQL library instructions to Frontier & Crusher user docs

---

systems/summit_user_guide.rst

This PR removes the hardcoded HPCToolkit version in Summit User Guide, and fixes the link to the HPCToolkit cheat sheet.

Update HPCToolkit section in Summit user guide

---

systems/crusher_quick_start_guide.rst
systems/frontier_user_guide.rst

Drafting a change in SBCAST instructions, which would leave the ROCm and CrayPE libraries in place, in their SquashFS file system. This change is shown to have negligible performance impact on Frontier.

Changed default sbcast to exclude some libraries on Crusher only

---

systems/crusher_quick_start_guide.rst
systems/frontier_user_guide.rst

Re-adding a paragraph & example script loaded with warnings for using `sbcast --exclude=NONE` on Frontier & Crusher.

Re-added exclude=NONE section on Crusher & Frontier SBCAST

---

index.rst

Updated Office Hour information displayed to the users. Added information on how to register for office hours through myOLCF instead of the WP site.

Updated OLCF Office Hour Information

---

systems/andes_user_guide.rst

Used Vim to fix a couple of capitalization errors found in the olcf user documentation for Andes while reading it over.

Fixed various capitalization errors

---

software/debugging/index.rst

Had to revert this back as the env vars need to be sourced on the compute side as well. The remote launch script with the vars is only needed if running forge client on local laptop

Modify reverse connect when using forge with local client

---

systems/crusher_quick_start_guide.rst
systems/frontier_user_guide.rst

When we determined that hipMallocManaged memory was backed by DDR with XNACK off we switched the "initial physical location" but forgot to update the behavior to make it consistent.
The table should now be correct for the current behavior.

Fix HSA_XNACK=0 hipMallocManaged access behavior

---

README.md

The link at the bottom of the README was a 404. Changed it to the current User Assistance page.

Fix broken link and adjust to OLCF User Assistance page

---

systems/frontier_user_guide.rst

As stated. Using ROCm 5.5 and later, rocBLAS and hipBLAS introduced some atomic operations to increase performance. Users can turn this off in rocBLAS/hipBLAS as described if repeatable results are desired.

Adding documentation regarding BLAS usage of atomic operations for Frontier

---

systems/crusher_quick_start_guide.rst
systems/frontier_user_guide.rst

This PR adds small sections detailing only the modules of omniperf and omnitrace. This does not deal with how to run these tools, as AMD maintains decent documentation for that, and the features move very quickly.

Add mini-sections for OmniPerf and OmniTrace

---

spi/index.rst

Currently login node names are not active; this PR would replace them with current logins.

Update login node names for CITADEL

---

systems/frontier_user_guide.rst

This is a one-word patch. I guess I needed more coffee when I wrote the earlier PR #792 ☕

Frontier: Fix typo on HPCViewer usage

---

accounts/olcf_policy_guide.rst
systems/frontier_user_guide.rst

updated policy guide to reflect new filesystems.
Removed extra '[' from lustre path on Frontier guide.

updating policy guide & fixing frontier guide table

---

software/python/parallel_h5py.rst

Removed libssh and openssl syntax

Python: updated mpi4py guide

---

systems/frontier_user_guide.rst

This patch adds basic instructions to use the oneAPI modules to use SYCL on Frontier.

Add basic instructions for using SYCL on Frontier

---

software/software-news.rst
systems/frontier_user_guide.rst

This includes information for the July 9, 2024 retirement of modules and July 16, 2024 default version updates.

Update Software News to include upcoming Frontier changes

---

software/software-news.rst
systems/frontier_user_guide.rst

Includes changes for the following:
- Greater emphasis on CRAY_LD_LIBRARY_PATH
- Adds section about compatible CrayPE modules
- Remove mention of amd-mixed in favor of ROCm
- Make changes to AMD moduleflow -- PrgEnv-amd now REQUIRES a `rocm` module to load the toolchain properly
- Updated information about `gcc-native`
- Updates Roofline computation to reflect new information provided by AMD during a roofline working group call.

Updated Frontier user guide for December 2023 PE update

---

systems/frontier_user_guide.rst

Removed the module spider warning, since we now have a new module spider utility on Frontier which contains patches that fix the earlier issues.
I also took this opportunity to improve the ROCm/MPICH compatibility sections, including adding a new note that describes how to use the CrayPE `rc.lua` files to effectively set your own default modules.

Removed module spider warning, added content to the ROCm/MPICH compatibility sections

---

systems/frontier_user_guide.rst

Beginning in ROCm/6.2.x, rocprofv3 is the recommended text-only profiler. Additionally, Omniperf and Omnitrace have been rebranded to ROCm Compute and Systems profilers.

Updating rocprof to include rocprofv3, updating Omnitrace/perf

---

systems/andes_user_guide.rst

This is to add a containers section to the Andes user guide.

Containers on Andes

---

systems/index.rst

Now that HPSS access has been removed we can remove the notable events page

Remove 2024 changes page from index

---

conf.py
software/index.rst
software/software_list/index.rst
software/software_list/software_list_group.html

This needs a software_list_group.json file to be placed in software/software_list by the documentation backend infrastructure.

Add software catalog page

---

systems/frontier_user_guide.rst

With the newer ROCm 6.4.x series, there is a new dlopen issue when using the "SBCASTing a binary with ALL libraries" technique for Frontier at scale. Added in the lines to the example script to add synbolic links for libamd_comgr.so

Fix documentation for using sbcast for ROCm 6.4.x binaries
